#!/usr/bin/python3
''' A python file that contains the class definition of a State and
an instance Base = declarative_base() '''

from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class State(Base):
    '''
     A class State inherits from Base
     id (Int) represents a autogenerated cloumn
     name(str) name of the state
     '''
    __tablename__ = 'states'

    id = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = Column(String(128), nullable=False)
    cities = relationship("City", cascade='all,\
            delete-orphan', backref="State")
