#!/usr/bin/python3
''' Python file similar to model_state.py named model_city.py
that contains the class definition of a City '''

from sqlalchemy import Column, Integer, String, ForeignKey
from model_state import Base


class City(Base):
    '''
     A class State inherits from Base
     id (Int) represents a autogenerated cloumn
     name(str) name of the state
     state_id(int) foreignkey for states table
     '''
    __tablename__ = 'cities'

    id = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)
